---
title: "Research"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---


## Papers Submitted and Under Review

* [1] **On the Mechanisms of Ability Peer Effects**, with <a href="https://sites.google.com/view/nsalamanca/home" target="_blank">Nicolás Salamanca</a>.\

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>Studying with higher ability peers increases student performance, yet we have little idea why. We exploit mandated random assignment of students to classrooms and find positive peer effects on test scores. With rich data on nineteen potential mechanisms, we then estimate how effects on attitudes, parents, and teachers could drive these results. Higher-achieving peers reduce student effort, increase student university aspirations, increase parental time investments and parental strictness, and have precise null effects elsewhere. None of these mechanisms, however, explain our peer effect on test scores. Our novel method to detect cluster violations of random assignment is of independent interest.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>Studying with higher ability peers increases student performance, yet we have little idea why. We exploit mandated random assignment of students to classrooms and find positive peer effects on test scores. With rich data on nineteen potential mechanisms, we then estimate how effects on attitudes, parents, and teachers could drive these results. Higher-achieving peers reduce student effort, increase student university aspirations, increase parental time investments and parental strictness, and have precise null effects elsewhere. None of these mechanisms, however, explain our peer effect on test scores. Our novel method to detect cluster violations of random assignment is of independent interest.</p>
</ul>

<ul class='wplists'>
**Working Paper**: <a href="https://adegendre.github.io/papers/deGendre_Salamanca_2020_Melbourne_Institute_WP_wp2020n19.pdf" target="_blank">Melbourne Institute (Oct 2020)</a> | <a href="https://adegendre.github.io/papers/deGendre_Salamanca_2020_IZA_dp13938.pdf" target="_blank">IZA (Dec 2020)</a> \
**Slides**: <a href="https://adegendre.github.io/papers/de_Gendre_Salamanca_ESAM_2021.pdf" target="_blank">Econometric Society Australasian Meeting (ESAM) (July 2021)</a> \
**Media**: <a href="https://theconversation.com/being-in-a-class-with-high-achievers-improves-students-test-scores-we-tried-to-find-out-why-171400" target="_blank">The Conversation (Nov 2021)</a> | ABC Radio Sydney Afternoons (15 Nov 2021)
</ul>


<br>

* [2] **Child Health and Parental Responses to an Unconditional Cash Transfer at Birth**, with John Lynch, Aurélie Meunier, Rhiannon Pilkington, and <a href="http://www.stefanie-schurer.com" target="_blank">Stefanie Schurer</a>.\

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>We estimate the impact on child health of the unanticipated introduction of the Australian Baby Bonus, a \$3,000 one-off unconditional cash transfer at birth. Using regression discontinuity methods and linked administrative data from South Australia, we find that treated babies had fewer preventable, acute, and urgent hospital presentations—medical care available without co-payments—in the first two years of life. The payment later increased demand for elective care, which requires planning, medical referrals, and often co-payments. Our effects are strongest for disadvantaged families. Our findings suggest that up to 34\% of the payout were recouped within the first year.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>We estimate the impact on child health of the unanticipated introduction of the Australian Baby Bonus, a \$3,000 one-off unconditional cash transfer at birth. Using regression discontinuity methods and linked administrative data from South Australia, we find that treated babies had fewer preventable, acute, and urgent hospital presentations—medical care available without co-payments—in the first two years of life. The payment later increased demand for elective care, which requires planning, medical referrals, and often co-payments. Our effects are strongest for disadvantaged families. Our findings suggest that up to 34\% of the payout were recouped within the first year.</p>
</ul>

<ul class='wplists'>
**Working Paper**: <a href="https://adegendre.github.io/papers/deGendre_Lynch_Meunier_Pilkington_Schurer_2021_IZA_dp14693.pdf" target="_blank">IZA (Sep 2021)</a>\
**Slides**: <a href="https://adegendre.github.io/papers/de_Gendre_NBER_SI_2022.pdf" target="_blank">NBER Summer Institute 2022 (July 2022)</a> 
</ul>

<br>


* [3] **Same-Sex Role Model Effects in Education**, with <a href="https://janfeld.weebly.com" target="_blank">Jan Feld</a>, <a href="https://sites.google.com/view/nsalamanca/home" target="_blank">Nicolás Salamanca</a> and <a href="http://ulfzoelitz.com" target="_blank">Ulf Zölitz</a>.

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>We study same-sex role model effects of teachers with a meta-analysis and our own study of three million students in 90 countries. Both approaches show that role model effects on performance are, on average, small: 0.030 SD in the meta-analysis and 0.015 SD in our multi-country study. Going beyond test scores, our multi-country study documents larger average role model effects on job preferences (0.063 SD). To understand the universality of these effects, we estimate the distributions of country-level same-sex role model effects. Although role model effects on test scores appear universally small, we find substantial cross-country variation for job preferences, with larger effects in countries with larger gender gaps. These results are consistent with role models inspiring students to overcome gender stereotypes and pursue a STEM career. However, in countries with negligible gender gaps, role models do not seem to have this equalizing function.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>We study same-sex role model effects of teachers with a meta-analysis and our own study of three million students in 90 countries. Both approaches show that role model effects on performance are, on average, small: 0.030 SD in the meta-analysis and 0.015 SD in our multi-country study. Going beyond test scores, our multi-country study documents larger average role model effects on job preferences (0.063 SD). To understand the universality of these effects, we estimate the distributions of country-level same-sex role model effects. Although role model effects on test scores appear universally small, we find substantial cross-country variation for job preferences, with larger effects in countries with larger gender gaps. These results are consistent with role models inspiring students to overcome gender stereotypes and pursue a STEM career. However, in countries with negligible gender gaps, role models do not seem to have this equalizing function.</p>
</ul>

<ul class='wplists'>
**Working Paper**: <a href="https://adegendre.github.io/papers/de Gendre Feld Salamanca Zoelitz 2023" target="_blank">University of Zurich Working Paper No. 438 (June 2023)</a> | <a href="https://www.role-model-effects.com" target="_blank">Website with interactive results</a>
</ul> 
  
  
<br>


* [4] **From Subsidies to Loans: The Effects of a National Student Finance Reform on the Choices of Secondary School Students**, with <a href="https://www.jankabatek.com" target="_blank">Jan Kabátek</a>.\

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>We analyse the effects of a national student finance reform in the Netherlands, which replaced universal subsidies for higher education students by low-interest loans. We show that this reform had a large impact on education choices of secondary school students, lowering their enrolments in college-preparing tracks and increasing the share of students specializing in STEM subjects. The reform also affected the living arrangements of new college entrants. Our findings highlight that secondary school students respond to the modes of higher education financing well ahead of their graduation, and that financial aid uncertainty alone can deter many from pursuing higher education.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>We analyse the effects of a national student finance reform in the Netherlands, which replaced universal subsidies for higher education students by low-interest loans. We show that this reform had a large impact on education choices of secondary school students, lowering their enrolments in college-preparing tracks and increasing the share of students specializing in STEM subjects. The reform also affected the living arrangements of new college entrants. Our findings highlight that secondary school students respond to the modes of higher education financing well ahead of their graduation, and that financial aid uncertainty alone can deter many from pursuing higher education.</p>
</ul>

<ul class='wplists'>
**Working Paper**: <a href="https://adegendre.github.io/papers/deGendre_Kabatek_2021_Melbourne_Institute_WP_wp2021n12.pdf" target="_blank">Melbourne Institute (July 2021)</a> | <a href="https://adegendre.github.io/papers/deGendre_Kabatek_2021_IZA_dp14686.pdf" target="_blank">IZA (Aug 2021)</a>
</ul>


<br>


* [5] **Two Decades of Welfare Reforms in Australia: How Did They Affect Single Mothers and Their Children?**, with <a href="http://www.stefanie-schurer.com" target="_blank">Stefanie Schurer</a> and Angela Zhang.\
  
<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>Worldwide, single mothers are profoundly time and income constrained, making them heavily reliant on government transfers. We examine how welfare reforms that introduced mutual obligations affected the economic position of single mothers and the development of their children over the past two decades in Australia. Using nationally representative longitudinal data, we show that disposable incomes of single-mother households were significantly reduced relative to partnered mothers since the 2005 Welfare-to-Work Act came into effect in July 2006, a downward trend that was aggravated by the Global Financial Crisis and the 2013 suspension of grandfathered single parenting payment rules. The reform diminished parenting and family payments for single mothers, who compensated income loss by increasing reliance on disability pension payments, work hours, and child-care expenditures. We then use nationally representative cohort data to estimate the impact of single motherhood on child skill development, following children who entered primary school when their mothers were affected by the Welfare-to-Work reform. We find unadjusted single-motherhood gaps of 0.2 SD in cognitive and 0.3 SD in non-cognitive skills. Non-cognitive skill gaps are only partially explained by differences in observable characteristics, while cognitive skill gaps are fully explained by observable characteristics. Differences in disposable household income between single and partnered mother households explain over 50% of the observed cognitive ability gaps in childhood and 25% in late adolescence. In the presence of positive spillover effects, we propose that welfare payments to vulnerable families may function as a social investment rather than a sunk cost.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>Worldwide, single mothers are profoundly time and income constrained, making them heavily reliant on government transfers. We examine how welfare reforms that introduced mutual obligations affected the economic position of single mothers and the development of their children over the past two decades in Australia. Using nationally representative longitudinal data, we show that disposable incomes of single-mother households were significantly reduced relative to partnered mothers since the 2005 Welfare-to-Work Act came into effect in July 2006, a downward trend that was aggravated by the Global Financial Crisis and the 2013 suspension of grandfathered single parenting payment rules. The reform diminished parenting and family payments for single mothers, who compensated income loss by increasing reliance on disability pension payments, work hours, and child-care expenditures. We then use nationally representative cohort data to estimate the impact of single motherhood on child skill development, following children who entered primary school when their mothers were affected by the Welfare-to-Work reform. We find unadjusted single-motherhood gaps of 0.2 SD in cognitive and 0.3 SD in non-cognitive skills. Non-cognitive skill gaps are only partially explained by differences in observable characteristics, while cognitive skill gaps are fully explained by observable characteristics. Differences in disposable household income between single and partnered mother households explain over 50% of the observed cognitive ability gaps in childhood and 25% in late adolescence. In the presence of positive spillover effects, we propose that welfare payments to vulnerable families may function as a social investment rather than a sunk cost.</p>
</ul>

<ul class='wplists'>
**Working Paper**: <a href="https://adegendre.github.io/papers/deGendre_Schurer_Zhang_2021_IZA_dp14752.pdf" target="_blank">IZA (Sep 2021)</a>
</ul>


## Work in Progress


* [1] **Class Rank and Sibling Spillover Effects**.

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>This paper studies how students' relative rank affects their younger siblings’ academic performance. Using Dutch administrative data, I exploit within-school, across-cohort variation in student rank. Consistent with previous research, I find that higher-ranked students experience faster human capital accumulation. Yet, these rank effects generate negative spillovers on younger siblings: a one standard deviation increase in rank decreases younger sibling’s test scores by 2 percent of a standard deviation. These spillovers are stronger for same-sex siblings. I show that changes in parental investments and expectations drive part of these spillovers. In particular, I show that migrant parents increase investments in school quality and speaking Dutch at home. My findings highlight that the peer environment creates within-family human capital spillovers.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>This paper studies how students' relative rank affects their younger siblings’ academic performance. Using Dutch administrative data, I exploit within-school, across-cohort variation in student rank. Consistent with previous research, I find that higher-ranked students experience faster human capital accumulation. Yet, these rank effects generate negative spillovers on younger siblings: a one standard deviation increase in rank decreases younger sibling’s test scores by 2 percent of a standard deviation. These spillovers are stronger for same-sex siblings. I show that changes in parental investments and expectations drive part of these spillovers. In particular, I show that migrant parents increase investments in school quality and speaking Dutch at home. My findings highlight that the peer environment creates within-family human capital spillovers.</p>
</ul>

<ul class='wplists'>
**Draft**: <a href="https://adegendre.github.io/papers/de_Gendre_2021_JMP_Class_Rank_and_Sibling_Spillover_Effects.pdf" target="_blank">JMP version (31 August 2022)</a> \
</ul>

<br>

* [2] **Cultural Integration in the Classroom: The Role of Students, Parents and Teachers**, with <a href="https://sites.google.com/site/kkarbownik/home?authuser=0" target="_blank">Krzysztof (Chris) Karbownik</a>, <a href="https://sites.google.com/view/nsalamanca/home" target="_blank">Nicolás Salamanca</a> and <a href="https://sites.google.com/site/yvesbzenou" target="_blank">Yves Zenou</a>.

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>The integration of ethnic minority students in the classroom could change the behaviors of ethnic majority students and their parents, as well as that of their teachers. Using random assignment of children to classrooms in Taiwanese middle schools, we show that exposure to Indigenous but not Hakka minorities lowers test scores of the ethnic majority students. These negative effects are primarily due to endogenous responses of parents and teachers rather than students’ correlated characteristics or responses.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>The integration of ethnic minority students in the classroom could change the behaviors of ethnic majority students and their parents, as well as that of their teachers. Using random assignment of children to classrooms in Taiwanese middle schools, we show that exposure to Indigenous but not Hakka minorities lowers test scores of the ethnic majority students. These negative effects are primarily due to endogenous responses of parents and teachers rather than students’ correlated characteristics or responses.</p>
</ul>

<ul class='wplists'>
**Status**: Draft in preparation. \
</ul> 


<br>

* [3] **The Impact of Low-Income Priorities Points on School Choice and Student Outcomes**, with <a href="https://sites.google.com/view/shushanikmargaryan" target="_blank">Shushanik Margaryan</a> and <a href="https://sites.google.com/site/josemontalbancastilla/" target="_blank">José Montalban Castilla</a>.

<!-- mobile code --> 
<details class="collapse-abstract">
  <summary>Abstract</summary>
  <p>We estimate the impact of income-based priority points on children’s’ outcomes and parental choices from preschool to Grade 6. With administrative records from Madrid, we use two sharp discontinuities in household income per capita which determine income-based priority points within the Boston mechanism. We first show that income-based priority points change parents’ strategy: low-income parents apply to fewer closer schools and schools with lower absenteeism, while higher-income parents apply to more demanded and higher-scoring schools. The priority points increase the likelihood that children are admitted to their preferred school. Yet, we find economically insignificant effects on standardized test scores 6 years later. Lastly, using a matched survey of parents and children, we find small negative effects on parental and child satisfaction with the school, teachers and peers. Our findings indicate that low and higher-income parents respond in sophisticated but different ways to priority rules under the Boston Mechanism.</p>
</details> 

<!-- desktop code --> 
<ul class='bigScreen'>
**Abstract**: \
<p>We estimate the impact of income-based priority points on children’s’ outcomes and parental choices from preschool to Grade 6. With administrative records from Madrid, we use two sharp discontinuities in household income per capita which determine income-based priority points within the Boston mechanism. We first show that income-based priority points change parents’ strategy: low-income parents apply to fewer closer schools and schools with lower absenteeism, while higher-income parents apply to more demanded and higher-scoring schools. The priority points increase the likelihood that children are admitted to their preferred school. Yet, we find economically insignificant effects on standardized test scores 6 years later. Lastly, using a matched survey of parents and children, we find small negative effects on parental and child satisfaction with the school, teachers and peers. Our findings indicate that low and higher-income parents respond in sophisticated but different ways to priority rules under the Boston Mechanism.</p>
</ul>

<ul class='wplists'>
**Status**: Analyzing new batch of data & Preparing first draft. Was just presented at SOLE Annual Meeting 2023. \
</ul> 


<br>

* [4] **College Information Provision to Disadvantaged Youth**, with Gloria Chen and <a href="https://siqipan.weebly.com" target="_blank">Siqi Pan</a>.

<ul class='wplists'>
**Status**: Designing field intervention. \
</ul>   

<br>


<!--

* [3] **Quantifying Aspirational Poverty Traps**, with <a href="https://sites.google.com/view/nsalamanca/home" target="_blank">Nicolás Salamanca</a>.
  + **Status**: Draft in preparation. 
  
<!-- mobile code --> 

<!--
<details class="collapse-abstract">
  <summary>Description</summary>
  <p>We propose a simple methodology based on a microeconomic model of human capital investment with goals and using threshold regression methods to estimate the size and location in the population of aspirational poverty traps. We apply our methodology to the United States using the NLSY79 and find that 5.5 to 7% of the population, around the 37th percentile of wealth, could be located in such poverty traps.</p>
</details> 

<!-- desktop code --> 

<!--
<ul class='bigScreen'>
**Description**: \
<p>We propose a simple methodology based on a microeconomic model of human capital investment with goals and using threshold regression methods to estimate the size and location in the population of aspirational poverty traps. We apply our methodology to the United States using the NLSY79 and find that 5.5 to 7% of the population, around the 37th percentile of wealth, could be located in such poverty traps.</p>
</ul>

<br>

Comments here 
-->
  
