---
title: "Resources"
---

On this page I share some resources that I found useful in some way or another. This page is work in progress, I add sections and resources as I find them. 


### Replicability and reproducibility

This is a topic that I find particularly important. I was lucky to have peers at Maastricht Uni with whom I could have great discussions about research practices, ethics and how to do our research the best we could -- big shoutout to <a href="https://sites.google.com/view/henrikzaunbrecher" target="_blank">Henrik Zaunbrecher</a> and to my amazing coauthors <a href="https://janfeld.weebly.com" target="_blank">Jan Feld</a>, <a href="https://sites.google.com/view/nsalamanca/home" target="_blank">Nicolás Salamanca</a> and <a href="http://ulfzoelitz.com" target="_blank">Ulf Zölitz</a> for giving me so much food for thought. We talked a lot about the *replication crisis* and the *file drawer problem* (among many things). Here are some resources I've found over the years that have nourished my thoughts on this topic, and have helped me progress in my own practices.

- This book <a href="http://emiguel.econ.berkeley.edu/books/transparent-and-reproducible-social-science-research/" target="_blank">**Transparent and Reproducible Social Science Research**</a> by Garret Christensen, Jeremy Freese, and Edward Miguel. A fantastic introduction into the issues of the replicability problems, the incentive problems in modern science and practical advice to improve our research practices to move forward collectively. It's also a relatively quick and easy read.\

- <a href="https://i4replication.org" target="_blank">**The Institute for Replication**</a> is a research lab led by Abel Brodeur and his team. They do amazing work to normalize replications, increase awareness around the need for replicating papers, and improving researchers' incentives to replicate the work of others and make their own work more replicable. They have tons of teaching resources to transmit best practices to students, check out their website!\

- <a href="http://datacolada.org" target="_blank">**Data Colada**</a> is a great blog maintained by Profs. Uri Simonsohn, Leif Nelson and Joe Simmons. This blog is a gem: they keep the tone light but they always making you see things from a new perspective. They do some very serious data forensic work, write about best practices (e.g. I LOVE their post about the Groundhogday package for versioning in R), and propose new ways to detect p-hacking -- among other topics. 

- People and institutions to follow who do very interesting work on meta-science: the <a href="https://www.bitss.org" target="_blank">**BITSS (Berkeley Initiative for Transparency in the Social Sciences)**</a>, Simine Vazine and Fiona Fidler who co-direct the <a href="https://www.metamelb.org" target="_blank">**MetaMelb Research Group**</a>. I also find a lot of inspiration in the work and blog of <a href="http://www.stat.columbia.edu/~gelman/" target="_blank">**Andrew Gelman**</a> and <a href="https://sites.google.com/view/rachaelmeager/home" target="_blank">**Rachael Meager**</a>. 


### Academic writing (especially in economics) 

Writing is a core part of our work as academics; I am always surprised to hear my junior peers say that they will invest in their writing skills later on in their career, as if writing doesn't matter for getting our papers published and actually surviving in academia. First of all, the quality of our prose DOES matter for getting our papers out (my co-author Jan Feld just published an experimental study on this!). Second, spending a bit of energy polishing our papers can be enjoyable, much like any craft that one hones with time. Here are some resources that I keep coming back to, especially when I need inspiration for writing: 

- the one and only <a href="https://www.amazon.com/Economical-Writing-Third-Thirty-Five-Persuasive-dp-022644807X/dp/022644807X/ref=dp_ob_title_bk" target="_blank">**Economical Writing**</a> by Deirdre McCloskey and Stephen Ziliak. This book is beautifully written, insightful and hilarious! I love their tip about writing down ideas on single pieces of paper or postits and playing with the order, and the tip about cutting every third word when polishing a text. 


<!-- ### Presentations -->



### Making a website using RMarkdown 

These are the resources I used to make my own website. I tried different things (Wordpress, Squarespace, Jekyll...), and I find that the easiest way by far to create a static website is to use R and host your page via Github Pages. Github allows you to host your website for free, update it super quickly, and will never bug (unlike those sneaker ruby gem updates for your Jekyll page...) :-) Sure, you could make your page using Google Sites, but making your own page from scratch is much more fun! 

- Start from Emily Zabor's super simple guide <a href="https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html" target="_blank">here</a>. Run through the complete guide first, before tweaking the design.
- Learn the basics of RMarkdown to create your own content:
  + RMarkdown basics <a href="https://rmarkdown.rstudio.com/authoring_basics.html" target="_blank">here</a>
  + More RMarkdown basics <a href="https://monashbioinformaticsplatform.github.io/2017-11-16-open-science-training/topics/rmarkdown.html" target="_blank">here</a> 
  + Making websites using RMarkdown <a href="https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html" target="_blank">here</a> 
- Then tweak the design of your website by digging into more advanced topics using more complete guides: 
  + This online book <a href="https://rstudio4edu.github.io/rstudio4edu-book/index.html" target="_blank">here</a> 
  + Yan Holtz's RMarkdown tips <a href="https://holtzy.github.io/Pimp-my-rmd/" target="_blank">here</a> 
  + Academic Icons (e.g. for your contact list) <a href="https://jpswalsh.github.io/academicons/" target="_blank">here</a> 
- Note: for more control, you may want to learn a bit about HTML for organizing content and CSS for styling.