---
title: "Talks"
---

### 2022

Jan-22	AEA/ASSA Conference	(scheduled)	\

### 2021

Dec-21  European Winter Meeting of the Econometric Society 2021 (scheduled) \
Dec-21  University of Potsdam Seminar (scheduled) \
Nov-21  Irish Postgraduate and Early Career Economics (IPECE) Workshop 2021 (scheduled) \
Sep-21  University of Wollongong Seminar \
Sep-21	Annual Conference of the European Society of Labour Economics (EALE) \
Aug-21	23rd Australia/New Zealand Labour Econometrics Workshop (LEW) \
Jun-21	HCEO-NES Online Summer School on Socioeconomic Inequality 2021	\
Jun-21	The University of Sydney MPP Seminar Series	\
Jun-21	11th International Workshop on Applied Economics of Education (IWAEE)	\
Jun-21	34th Annual Meeting of the European Society of Population Economics	\
Jun-21	Swedish Institute for Social Research Seminar Series (SOFI, Stockholm University)	\

### 2020

Nov-20	The University of Sydney MPP Seminar Series	\

### 2019

Sep-19	University of Potsdam 6th PhD Workshop in Empirical Economics	\
Jun-19	10th International Workshop on Applied Economics of Education (IWAEE)	\
May-19	Workshop on The Effectiveness of Children's Education Around the Globe, European University Institute	\
May-19	University College Dublin Seminar Series	\
Apr-19	2nd IZA/Briq Behavioral Economics of Education Workshop	\

### 2018

Oct-18	3rd IZA Economics of Education Workshop	\
Oct-18	Applied Micro Workshop of the Department of Economics, The University of Melbourne	\
Aug-18	21st Labor Econometrics Workshop	\
Jun-18	9th International Workshop on Applied Economics of Education (IWAEE)	\
Jun-18	32nd Annual Meeting of the European Society of Population Economics	\
Jun-18	IZA World Labor Conference	\
May-18	IZA 21st Summer School in Labor Economics	\
Apr-18	University of Melbourne Department of Economics Seminar Series	\
Apr-18	RMIT Seminar Series	\

### 2017

Dec-17	Maastricht University School of Economics	\
Oct-17	Victoria University at Wellington Seminar Series	\
Aug-17	32nd Annual Congress of the European Economic Association and 70th European Meeting of the Econometric Society	\
Jun-17	8th International Workshop on Applied Economics of Education (IWAEE)	\
Jun-17	European Society of Population Economics	\

### 2016

Dec-16	Maastricht University DUHR Seminar Series	\
Oct-16	Melbourne Institute Seminar Series	\
Sep-16	3rd Annual Meeting of the Berlin Interdisciplinary Education Network	\
May-16	Dynamics of Inequalities and their Perceptions, Aix-Marseille Université	\


<!--
Add separation here between body and footer
-->

